revops_project:
  outputs:
    dev:
      type: postgres
      dbname: revops_database
      host: localhost
      pass: farrux05
      port: 5432
      schema: raw
      threads: 4
      user: farrux

    duckdb_dev:
      type: duckdb
      path: './duckdb/revops_analytics.duckdb'
      schema: marts

  target: dev
